version: '3.1'

services:
  postgresql:
    image: postgres:9.6

    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  pgcli:
    build:
      context: .
      dockerfile: Dockerfile_pgcli

    command: tail -f cat /var/log/dpkg.log

    environment:
      - POSTGRES_STRING=postgres://postgres:mypassword@postgresql/mydb
